server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://192.168.52.128:3306/order_db?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

